"""empty message

Revision ID: 5a7b6d620dfa
Revises: f587c86af37c
Create Date: 2021-02-08 05:18:15.002404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7b6d620dfa'
down_revision = 'f587c86af37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # creating a new Non Null column must be done in steps:
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.execute("UPDATE todos SET list_id = 1 WHERE list_id IS NULL;")
    op.alter_column('todos', 'list_id', nullable=False)
    # create an initial list to which all existing todos will be assigned
    op.execute("INSERT INTO todolists (id, name) VALUES (1, 'Unspecified');")
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
