"""empty message

Revision ID: f587c86af37c
Revises: 25379f2aea03
Create Date: 2021-02-07 09:17:06.150014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f587c86af37c'
down_revision = '25379f2aea03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE todos SET completed = False WHERE completed IS NULL;")
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
